version: '3.7'
services:
  timescaledb:
    hostname: postgres
    image: timescale/timescaledb:latest-pg12
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - "timescaledb-data:/var/lib/postgresql/data"
      - ./data/:/docker-entrypoint-initdb.d:rwx
    env_file:
      - dev.env

  app:
    build: .
    volumes:
      - ./:/app
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=homework
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

  
volumes:
  timescaledb-data:
